DO $$ BEGIN CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN', 'PROJECT_MANAGER', 'SALES_AGENT', 'DEVELOPER'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "ProjectStatus" AS ENUM ('INTAKE', 'PLANNING', 'IN_PROGRESS', 'IN_REVIEW', 'REVISION', 'COMPLETE', 'ON_HOLD', 'CANCELLED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "Priority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "FileKind" AS ENUM ('BRIEF', 'ASSET', 'CONTRACT', 'INVOICE', 'REFERENCE', 'DELIVERABLE', 'OTHER'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS "Organization" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "slug" TEXT NOT NULL UNIQUE, "logoUrl" TEXT, "primaryColor" TEXT NOT NULL DEFAULT '#183d35', "featureFlags" JSONB NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "Membership" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL REFERENCES "Organization"("id") ON DELETE CASCADE, "userId" TEXT NOT NULL, "displayName" TEXT NOT NULL, "role" "Role" NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("organizationId", "userId"));
CREATE TABLE IF NOT EXISTS "Project" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL REFERENCES "Organization"("id") ON DELETE CASCADE, "name" TEXT NOT NULL, "clientName" TEXT NOT NULL, "clientWebsite" TEXT, "clientPhone" TEXT, "packageName" TEXT, "status" "ProjectStatus" NOT NULL DEFAULT 'INTAKE', "priority" "Priority" NOT NULL DEFAULT 'MEDIUM', "requirements" TEXT, "deadline" TIMESTAMP(3), "googleMapsUrl" TEXT, "demoUrl" TEXT, "githubUrl" TEXT, "vercelUrl" TEXT, "revisionCount" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "developerId" TEXT REFERENCES "Membership"("id") ON DELETE SET NULL, "managerId" TEXT REFERENCES "Membership"("id") ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS "ProjectFile" ("id" TEXT PRIMARY KEY, "projectId" TEXT NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE, "kind" "FileKind" NOT NULL DEFAULT 'OTHER', "name" TEXT NOT NULL, "storageKey" TEXT NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("projectId", "storageKey", "version"));
CREATE TABLE IF NOT EXISTS "Revision" ("id" TEXT PRIMARY KEY, "projectId" TEXT NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE, "notes" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "Activity" ("id" TEXT PRIMARY KEY, "projectId" TEXT NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE, "actorId" TEXT NOT NULL, "action" TEXT NOT NULL, "metadata" JSONB NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "AuditLog" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL REFERENCES "Organization"("id") ON DELETE CASCADE, "actorId" TEXT, "action" TEXT NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT, "metadata" JSONB NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS "Membership_organizationId_role_idx" ON "Membership"("organizationId", "role");
CREATE INDEX IF NOT EXISTS "Project_organizationId_status_idx" ON "Project"("organizationId", "status");
CREATE INDEX IF NOT EXISTS "Project_organizationId_deadline_idx" ON "Project"("organizationId", "deadline");
CREATE INDEX IF NOT EXISTS "Activity_projectId_createdAt_idx" ON "Activity"("projectId", "createdAt");
CREATE INDEX IF NOT EXISTS "AuditLog_organizationId_createdAt_idx" ON "AuditLog"("organizationId", "createdAt");
ALTER TABLE "Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Membership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Project" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProjectFile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Revision" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Activity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
CREATE FUNCTION public.is_org_member(org_id TEXT) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM "Membership" WHERE "organizationId" = org_id AND "userId" = auth.uid()::text AND "isActive" = true) $$;
CREATE POLICY "members read their organization" ON "Organization" FOR SELECT USING (public.is_org_member(id));
CREATE POLICY "members read memberships" ON "Membership" FOR SELECT USING (public.is_org_member("organizationId"));
CREATE POLICY "members read projects" ON "Project" FOR SELECT USING (public.is_org_member("organizationId"));
CREATE POLICY "members read project files" ON "ProjectFile" FOR SELECT USING (EXISTS (SELECT 1 FROM "Project" p WHERE p.id = "ProjectFile"."projectId" AND public.is_org_member(p."organizationId")));
CREATE POLICY "members read revisions" ON "Revision" FOR SELECT USING (EXISTS (SELECT 1 FROM "Project" p WHERE p.id = "Revision"."projectId" AND public.is_org_member(p."organizationId")));
CREATE POLICY "members read activity" ON "Activity" FOR SELECT USING (EXISTS (SELECT 1 FROM "Project" p WHERE p.id = "Activity"."projectId" AND public.is_org_member(p."organizationId")));
CREATE POLICY "admins read audits" ON "AuditLog" FOR SELECT USING (EXISTS (SELECT 1 FROM "Membership" m WHERE m."organizationId" = "AuditLog"."organizationId" AND m."userId" = auth.uid()::text AND m.role = 'SUPER_ADMIN' AND m."isActive" = true));
