ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "paymentStatus" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "branding" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "references" JSONB NOT NULL DEFAULT '[]';
