"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function NewProjectPage() {
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); const form = new FormData(event.currentTarget); const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) { location.assign("/auth"); return; }
    const { data: memberships, error: membershipError } = await supabase.from("Membership").select("organizationId").eq("userId", user.id).limit(1); if (membershipError || !memberships?.length) { setMessage("Create a workspace before creating a project."); setSaving(false); return; }
    const clean = (key: string) => String(form.get(key) || "").trim() || null;
    const { data: project, error } = await supabase.from("Project").insert({ id: crypto.randomUUID().replaceAll("-", ""), organizationId: memberships[0].organizationId, name: clean("name"), clientName: clean("clientName"), packageName: clean("packageName"), clientWebsite: clean("clientWebsite"), clientPhone: clean("clientPhone"), googleMapsUrl: clean("googleMapsUrl"), demoUrl: clean("demoUrl"), githubUrl: clean("githubUrl"), vercelUrl: clean("vercelUrl"), requirements: clean("requirements"), notes: clean("notes"), paymentStatus: clean("paymentStatus"), priority: clean("priority") || "MEDIUM", deadline: clean("deadline"), updatedAt: new Date().toISOString() }).select("id").single();
    if (error || !project) { setMessage(error?.message || "Could not create project."); setSaving(false); return; }
    await supabase.from("Activity").insert({ id: crypto.randomUUID().replaceAll("-", ""), projectId: project.id, actorId: user.id, action: "Project created" }); location.assign("/projects"); }
  const input = "mt-1 w-full rounded-lg border border-[#dce4df] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#39745f]";
  return <main className="min-h-screen bg-[#f7f8f6] px-5 py-10 text-[#202523]"><form onSubmit={submit} className="mx-auto max-w-3xl"><Link href="/projects" className="text-sm font-bold text-[#286a5a]">← Projects</Link><div className="mt-5 rounded-xl border border-[#e0e5e1] bg-white p-7"><p className="text-xs font-bold tracking-[.15em] text-[#5f796f]">PROJECT INTAKE</p><h1 className="mt-2 font-serif text-3xl">Create a project</h1><p className="mt-2 text-sm text-[#718079]">Capture the brief, client details, links, and delivery context in one place.</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Project name" name="name" required className={input}/><Field label="Client name" name="clientName" required className={input}/><Field label="Package" name="packageName" className={input}/><Field label="Payment status" name="paymentStatus" placeholder="Deposit received" className={input}/><Field label="Client website" name="clientWebsite" type="url" className={input}/><Field label="Client phone" name="clientPhone" className={input}/><Field label="Deadline" name="deadline" type="date" className={input}/><label className="text-sm font-bold">Priority<select name="priority" className={input} defaultValue="MEDIUM"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></label><Field label="Google Maps URL" name="googleMapsUrl" type="url" className={input}/><Field label="Demo URL" name="demoUrl" type="url" className={input}/><Field label="GitHub URL" name="githubUrl" type="url" className={input}/><Field label="Vercel URL" name="vercelUrl" type="url" className={input}/></div><label className="mt-5 block text-sm font-bold">Requirements<textarea name="requirements" className={input} rows={5} placeholder="Goals, scope, deliverables, constraints…"/></label><label className="mt-5 block text-sm font-bold">Internal notes<textarea name="notes" className={input} rows={3} placeholder="Client context and delivery notes…"/></label>{message && <p className="mt-5 rounded-lg bg-[#fff0ed] p-3 text-sm text-[#a34c3b]">{message}</p>}<div className="mt-7 flex justify-end gap-3"><Link href="/projects" className="rounded-lg px-4 py-3 text-sm font-bold">Cancel</Link><button disabled={saving} className="rounded-lg bg-[#1d443b] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{saving ? "Creating…" : "Create project"}</button></div></div></form></main>;
}
function Field({ label, name, className, required, type = "text", placeholder }: { label: string; name: string; className: string; required?: boolean; type?: string; placeholder?: string }) { return <label className="text-sm font-bold">{label}<input name={name} type={type} required={required} placeholder={placeholder} className={className}/></label>; }
